version: "0.1"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DOCKERIZED=true
    volumes:
      - ./app:/rails/app
      - ./swagger:/rails/swagger
      - ./spec:/rails/spec
      - ./db/migrate:/rails/db/migrate
    
    ports:
      - "3000:3000"
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES-db: footballai-back-dev-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
    environment:
      - ADMINER_DEFAULT_SERVER=db  # Change default server to PostgreSQL
      - ADMINER_DEFAULT_DATABASE=footballai-back-dev-db
      - ADMINER_DEFAULT_USERNAME=postgres
      - ADMINER_DEFAULT_PASSWORD=root
