version: "0.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DOCKERIZED=true
    volumes:
      - ./app:/rails/app
      - ./db/migrate:/rails/db/migrate
      - ./config:/rails/config

    ports:
      - "3000:3000"
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES-db: guess-all-dev-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db # Change default server to PostgreSQL
      - ADMINER_DEFAULT_DATABASE=guess-all-dev-db
      - ADMINER_DEFAULT_USERNAME=root
      - ADMINER_DEFAULT_PASSWORD=root
