---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: john_doe
                name:
                  type: string
                  example: John
                surname:
                  type: string
                  example: Doe
                birthdate:
                  type: string
                  format: date
                phone_number:
                  type: string
                  example: '1234567890'
                email_address:
                  type: string
                  example: johndoe@ex.it
                password_digest:
                  type: string
                  example: password
                state:
                  type: string
                  example: italy
                city:
                  type: string
                  example: rome
                address:
                  type: string
                  example: via roma 1
              required:
              - username
              - name
              - surname
              - birthdate
              - phone_number
              - email_address
              - password_digest
              - state
              - city
              - address
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    username:
                      type: string
                    name:
                      type: string
                    surname:
                      type: string
                    birthdate:
                      type: string
                      format: date
                    phone_number:
                      type: string
                    email_address:
                      type: string
                    password_digest:
                      type: string
                    state:
                      type: string
                    city:
                      type: string
                    address:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - username
                  - name
                  - surname
                  - birthdate
                  - phone_number
                  - email_address
                  - password_digest
                  - state
                  - city
                  - address
                  - created_at
                  - updated_at
        '404':
          description: no table users found
  "/users/{id}":
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  name:
                    type: string
                  surname:
                    type: string
                  birthdate:
                    type: string
                    format: date
                  phone_number:
                    type: string
                  email_address:
                    type: string
                  password_digest:
                    type: string
                  state:
                    type: string
                  city:
                    type: string
                  address:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - username
                - name
                - surname
                - birthdate
                - phone_number
                - email_address
                - password_digest
                - state
                - city
                - address
        '404':
          description: user not found
    put:
      summary: Updates a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user updated
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                surname:
                  type: string
                birthdate:
                  type: string
                  format: date
                phone_number:
                  type: string
                email_address:
                  type: string
                password_digest:
                  type: string
                state:
                  type: string
                city:
                  type: string
                address:
                  type: string
    delete:
      summary: Deletes a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: user deleted
        '404':
          description: user not found
servers:
- url: http://localhost:3000
  description: Main server for API V1
