default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: footballai-back-dev-db

test:
  <<: *default
  database: your_test_database_name

production:
  <<: *default
  database: your_production_database_name
  host: your_production_database_host
  username: your_production_database_username
  password: your_production_database_password
