default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DOCKERIZED'] ? 'db' : 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: guess-who-football-edition-dev-db

test:
  <<: *default
  database: guess-who-football-edition-test-db

production:
  <<: *default
  database: guess-who-football-edition-prod-db
  host: your_production_database_host
  username: your_production_database_username
  password: your_production_database_password
